# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       : Template  # The title of the book. Will be placed in the left navbar.
author                      : ADM  # The author of the book
copyright                   : "2025"  # Copyright year to be placed in the footer
logo                        : "https://github.com/jhufena/jhufena.github.io/blob/main/png/hub_and_spoke.jpg?raw=true"  # A path to the book logo
email                       : "abikesa.sh@gmail.com"
exclude_patterns            : ["LICENSE.md"]  # Patterns to skip when building the book. Can be glob-style (for example "*skip.ipynb")

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : ["LICENSE.md"]  # A list of patterns to *skip* in execution (for example a notebook that takes a really long time)

#######################################################################################
# HTML-specific settings
html:
  navbar_number_sections    : False  # Add a number to each section in your left navbar
  home_page_in_navbar       : False  # Whether to include your home page in the left Navigation Bar; I like this!!!!!!!
  use_repository_button     : False  # Whether to add an "Repository" button to pages. If `true`, repository information in repository: must be filled in
  use_issues_button         : False  # Whether to add an "Open issue" button to pages. If `true`, repository information in repository: must be filled in
  use_edit_page_button      : False  # Whether to add an "Suggest edit" button to pages. If `true`, repository information in repository: must be filled in
  extra_footer              : |
    The Artist is the creator of beautiful things
  comments:
    hypothesis              : False # For data collection in top right corner
  extra_css:
    - "_static/custom.css"

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "classic"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (for example, https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (for example, https://datahub.berkeley.edu)
  thebelab                  : false  # Add a thebelab button to pages (requires the repository to run on Binder)

repository:
  url                       : https://github.com/abikesa/template # The URL to your book's repository
  path_to_book              : "book/website"  # A path to your book's folder, relative to the repository root.
  branch                    : main

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :
      - 'sphinx_panels'
      - 'sphinxcontrib.bibtex'
  config                    :  # key-value pairs to directly over-ride the Sphinx configuration
    language                : en
    html_show_copyright     : false
    suppress_warnings       :
        - 'app.add_node'
        - 'app.add_directive'
        - 'app.add_role'
    myst_heading_anchors    : 5
    bibtex_bibfiles         :
      - _bibliography/references.bib
    bibtex_reference_order: 'citation' 
    bibtex_default_style: 'unsrt' # 'plain' 
    bibtex_reference_style: 'label' # 'author_year'  
    bibtex_cite_style: 'numeric'
    bibtex_footbibliography_header: ''
